# Chapter 2. A pragmatic approach

## The essence of good design

The ETC principle - easy to change

*Good design is easier to change than bad design*

## DRY - The evils of duplication

*Every piece of knowledge must have a single, unambiguous, authoritative representation within a system*

- Level 1 DRY - Don't copy and paste lines of code. 
- Level 2 DRY - Use self-explanatory names
- Level 3 DRY - Isolate one idea to one part in the data structure
- Level 4 DRY - Create systems that are single sources of truth
- Level 5 DRY - Communicate all knowledge across your team

## Orthogonality

*In a well-designed system, changes to individual components generally do not effects on other components*

> You want to design components that are self-contained: independent, and with a single, well-defined purpose ...

Other words for orthogonality:
- modular
- component-based
- layered

<!--

### Toolkits and libraries

> When you bring in a toolkit (or even a library from other members of your team), ask yourself whether it imposes changes on your code that shouldn't be there. 

-->

## Reversibility

> The mistake lies in assuming that any decision is cast in stone—and in not preparing for the contingencies that might arise. Instead if carving decisions in stone, think of them more as being written in the sand at the beach. A big wave can come and wipe them out at any time.

## Tracer bullets

## Prototypes and Post-it notes

## Domain languages

## Estimating




